import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const session = await auth();

  return (
    // <SessionProvider session={session}>
    <html lang="en">
      <body className={`bg-black dark w-full min-h-screen antialiased box1 `}>{children}</body>
    </html>
    // </SessionProvider>
  );
}
